#!/bin/sh

# https://github.com/thisdougb/git-time-hooks
#
# This hook runs before the partner prepare-commit-msg hook. It
# stamps each commit with the creation time of the current branch.

HOOKNAME=commit-msg

# dot delimited list of branches to ignore
EXCLUDE_BRANCHES=".master.main."

BRANCH=$(git symbolic-ref HEAD --short)
NOW=$(date +%s)
# date options for compatibility on mac and linux
ONEMONTHAGO=$(date -v-1m +%s 2>/dev/null || date -d "1 month ago" +%s)

if [ -n "$BRANCH" ]; then

    # a bit of a shell script hack
    echo "$EXCLUDE_BRANCHES" | grep ".$BRANCH."
    if [ $? = 0 ]; then
        echo "[$HOOKNAME] ignoring branch $BRANCH, not adding branch timestamp"
      exit 0
    fi

    # the reflog is created after the first commit is made. so avoid a spurious
    # error with this check.
    git reflog >/dev/null 2>&1
    if [ $? != 0 ]; then
        echo "[$HOOKNAME] reflog does not exist yet"
      exit 0
    fi

    # git reflog: list (local) reflog entries in the last month
    # grep1: we don't specify the from branch
    # grep2: make sure we're checking out our target
    # tail: get the last/older occurence
    # sed: strip out the timestamp (basic POSIX regex for compatibility)
    AGE=$(git reflog show --date=unix --since=$ONEMONTHAGO --format="%gd %gs" \
          | grep "checkout: moving from " \
          | grep " to $BRANCH" \
          | tail -1 \
          | sed 's/HEAD@{\([0-9]\+\)}.*/\1/g')

    # include the branch name so the post-merge hook is a little safer
    echo "\ntime_branch_created $BRANCH $AGE" >> "$1"
fi
